GET http://localhost:5010/v1.0/invoke/service1/method/ HTTP/1.1


###


GET http://localhost:5011/v1.0/invoke/service2/method/ HTTP/1.1




###


GET http://localhost:5012/v1.0/invoke/service3/method/ HTTP/1.1

###


GET http://localhost:5010/v1.0/invoke/service3/method/ HTTP/1.1


###

GET http://localhost:5010/v1.0/invoke/service1/method/calculate/6/3 HTTP/1.1


###
POST http://localhost:5010/v1.0/state/statestore HTTP/1.1
Content-Type: application/json

[{
    "key": "userSettings",
    "value":{
        "selectedColor": "red",
        "isVip": true
    }
}]


###
GET http://localhost:5010/v1.0/state/statestore/userSettings HTTP/1.1


###
GET http://localhost:5010/v1.0/invoke/service1/method/setstate/name/aster HTTP/1.1

###
GET http://localhost:5010/v1.0/invoke/service1/method/getstate/name HTTP/1.1


###
GET http://localhost:5010/v1.0/secrets/local-secret-store/redisPassword HTTP/1.1

###
GET http://localhost:5010/v1.0/invoke/service1/method/secret/redisPassword HTTP/1.1


###
GET http://localhost:5010/v1.0/invoke/service1/method/secret/redisPassword HTTP/1.1


###
GET http://localhost:5010/v1.0/invoke/service1/method/secret/redisPassword HTTP/1.1



###
GET http://localhost:5010/v1.0/invoke/service1/method/createorder HTTP/1.1
